#mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/mylife?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    druid:
      max-active: 20
      initial-size: 1
      min-idle: 3 #最小空闲值.当空闲的连接数少于阀值时，连接池就会预申请去一些连接，以免洪峰来时来不及申请。
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      filters: stat,wall,slf4j

#mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    local-cache-scope: session #一级缓存
    cache-enabled: true #二级缓存
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.mylife.entity


#日志
#logging:
#  level:
#    com.mylife.mapper: debug
